server:
  port: 10001
spring:
  application:
    name: doctor-service
# standalone instance
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  security:
    enabled: false
#eureka:
#  client:
#    backup-registry-impl: